# This docker compose file is for building and running a production version of Massive Decks.
# This uses the built images from the docker hub.
# This version also configures a postgres server for data storage.

version: "3"

networks:
    internal:

services:
    server:
        container_name: server
        # If you want to keep your deployment stable, it would be sensible to specify a specific tag rather than just `latest` here.
        # Make sure you always deploy the same tag for client and server.
        image: "ihasdapie/humerusdecks_server:latest"
        # depends_on:
        #     - storage
        environment:
            - NODE_ENV=production
            # This needs to be changed to a secret value.
            # You can run `npm run generate-secret` in the server project to generate an appropriate value.
            - MD_SECRET=CHANGEME
        networks:
            - internal
        volumes:
            # This mounts a new configuration file over the default one, which is easier than building a whole new image on top of the normal one with a new config file.
            # Note the path to the local file will need changing to the real location.
            - /home/ihasdapie/Projects/UTMIST/theHumerusBot/humerusdecks/deployment/postgres/config.json5:/md/config.json5:ro
        restart: unless-stopped

    client:
        container_name: client
        # If you want to keep your deployment stable, it would be sensible to specify a specific tag rather than just `latest` here.
        # Make sure you always deploy the same tag for client and server.
        image: "ihasdapie/humerusdecks_client:latest"
        depends_on:
            - server
        ports:
            - "80:8080"
        networks:
            - internal
        restart: unless-stopped
